### ISSUE TITLE
Always 404

### ISSUE THREAD

**Issue by caam1406** [dhmgroup/dart-wp#10]
I'm try do work with the sample:
import 'package:wordpress_api/wordpress_api.dart';

WordPressAPI api = WordPressAPI('https://jsonplaceholder.typicode.com/');

void main() async {
  final wp = WordPressAPI('https://jsonplaceholder.typicode.com/posts');
  final posts = await wp.getPosts();
  for (final post in posts) {
    print(post.title['rendered']);
  }
}
But always return 404:
Exception: DioError [DioErrorType.RESPONSE]: Http status error [404]
#0      WordPressAPI.getAsyc (package:wordpress_api/src/main.dart:249:7)
<asynchronous suspension>
#1      WordPressAPI.getPosts (package:wordpress_api/src/main.dart:281:23)
#2      main (package:mercurio_comunicator/getcardContent.dart:7:26)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by theeomm** [comment]
This package is a WordPress API wrapper and can only be used with a WordPress site. `'https://jsonplaceholder.typicode.com` is not a WordPress powered website.

**Comment by caam1406** [comment]
Thanks;
