### ISSUE TITLE
Exmaple App

### ISSUE THREAD

**Issue by 2shrestha22** [dhmgroup/dart-wp#14]
We need example app for this library. I am new to programming and having problem with this package.

Here is code and I don't know data type so put List<dynamic> in return. How should I do if I don't want to put dynamic all over the app code and need a model?
```
 Future<List<dynamic>> fetchPosts(int pageNum) async {
    return wp.getPosts();
  }
}
```

**Comment by theeomm** [comment]
Please confirm that the latest update fixed your issue. Otherwise, this issue will be closed.

**Comment by 2shrestha22** [comment]
thanks..
