### ISSUE TITLE
Cast Error

### ISSUE THREAD

**Issue by 2shrestha22** [dhmgroup/dart-wp#15]
Using this library with WordPress sites that have `meta` value in getPosts cause cast error.  With the site which have empty meta, `meta = [ ]` (in JSON ) library is working properly. WordPress API send meta as a map,
```
"meta": {
            "spay_email": "",
            "jetpack_publicize_message": ""
        },
```
in this case library gives type error.

**Comment by theeomm** [comment]
Thank you for your feedback. We are looking at pushing a fix shortly.

**Comment by 2shrestha22** [comment]
waiting for the fix.

**Comment by theeomm** [comment]
This issue has been resolved now.
