### ISSUE TITLE
Caching of API Requests for offline usage

### ISSUE THREAD

**Issue by llorenzo** [dhmgroup/dart-wp#19]
Ist that something that could be implemented?
In combination of image caching this could help for offline usage.

**Comment by theeomm** [comment]
A great suggestion that may be considered. For now, this suggestion will be left open to the community while I focus on the implementation of authorized requests.

**Comment by theeomm** [comment]
As of v0.3, caching can be implemented with the initialization of a custom Dio instance with an interceptor like [Dio HTTP Cache Interceptor](https://pub.dev/packages/dio_cache_interceptor). Thank you for the suggestion
