### ISSUE TITLE
Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'String?'

### ISSUE THREAD

**Issue by dariolr** [dhmgroup/dart-wp#21]
[can you solve this?](https://github.com/dhmgroup/dart-wp/issues/20#issuecomment-822576885)

thank you

**Comment by Sabatin** [comment]
Still waiting with you. Some news?

**Comment by theeomm** [comment]
It has been updated on the dev branch.

**Comment by theeomm** [comment]
Solved in v0.3.1+
