### ISSUE TITLE
No get method found.

### ISSUE THREAD

**Issue by syan-park** [dhmgroup/dart-wp#24]
Hey, guys.

in your sample code.
Retrieve data from a custom endpoint.

My code makes error. 
The method 'get' isn't defined for the type 'WordPressAPI'.
Try correcting the name to the name of an existing method, or defining a method named 'get'.

```
  void main() async {
    final api = WordPressAPI('wp-site.com');
    final WPResponse res = await api.get(endpoint: 'your-custom-endpoint');
    print(res.data);
  }
```

**Comment by theeomm** [comment]
Sorry for the mistake. Forgot to update the example in the docs. `get` method has been changed to `fetch`. This was included in the [changelog](https://pub.dev/packages/wordpres).
