### ISSUE TITLE
Problem with local server

### ISSUE THREAD

**Issue by kalismeras61** [dhmgroup/dart-wp#25]
Hello I have installed wordpress on local mamp server. So when i want to fetch post from local server i am getting below errors.

 #0   packages/wordpress_api/src/main.dart 160:18                          _discover
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ DioError [DioErrorType.response]: XMLHttpRequest error.
│ ⛔ dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 906:28   get current
│ ⛔ packages/dio/src/dio_mixin.dart 819:20                               assureDioError
│ ⛔ packages/dio/src/dio_mixin.dart 678:13                               _dispatchRequest
│ ⛔ dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 60:31   <fn>
│ ⛔ dart-sdk/lib/async/zone.dart 1617:54                                 runBinary
│ ⛔ dart-sdk/lib/async/future_impl.dart 166:20                           handleError
│ ⛔ dart-sdk/lib/async/future_impl.dart 716:46                           handleError
│ ⛔ dart-sdk/lib/async/future_impl.dart 737:13                           _propagateToListeners
│ ⛔ dart-sdk/lib/async/future_impl.dart 547:5                            [_completeError]
│ ⛔ dart-sdk/lib/async/future_impl.dart 603:7                            callback
│ ⛔ dart-sdk/lib/async/schedule_microtask.dart 40:11                     _microtaskLoop
│ ⛔ dart-sdk/lib/async/schedule_microtask.dart 49:5                      _startMicrotaskLoop

**Comment by kalismeras61** [comment]
It looks like CORS issue with Flutter.

**Comment by zkmark** [comment]
Resolved
https://github.com/hillelcoren/flutter-redux-starter/issues/16#issuecomment-544113736

If you are in localhost you must put your ip address

To get it in cmd
`ipconfig`

And copy the IPv4 Address.
