### ISSUE TITLE
Do you remove html tags from response ?

### ISSUE THREAD

**Issue by kalismeras61** [dhmgroup/dart-wp#26]
Hello, i have post which has HTML tags in content but in response it is showing without tags. Is it normal ?

**Comment by theeomm** [comment]
Yes, this is the normal behavior. HTML tags are stripped using the HTML package. Do you need the tags for any reason?

**Comment by kalismeras61** [comment]
I think we should keep also HTML tags. Because i can handle them on using html package. Or there can be one more field like

"htmlContent"  something like that.

**Comment by theeomm** [comment]
Great suggestion, I will push an update soon

**Comment by GreenCappuccino** [comment]
It seems that the package doesn't pre-render HTML now, which is nice. We are using the latest commit in our pubspec. However, it's still ideal to have it on pub.dev. When is it possible for that to happen? Thanks.

**Comment by theeomm** [comment]
This has been resolved in the latest release [v1.2.0](https://pub.dev/packages/wordpress_api/versions/1.2.0)
