### ISSUE TITLE
Add more abstraction 

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [dhmgroup/dart-wp#3]
Thanks for the package! I believe you should add more extraction, like a function called getPosts() for fetching posts instead of leaving it up to the dev to read the wp api first. This is how other api clients are written, and it'll also prevent more errors from misspelled endpoints.

**Comment by theeomm** [comment]
Thanks for the suggestion, the abstract classes will be added pretty soon. However, contributions to the package are welcome.

**Comment by ThinkDigitalSoftware** [comment]
Cool. any reason why this issue is closed then if it's still in progress?

**Comment by theeomm** [comment]
I closed the issue becuase an update has been released. The functions were added in the latest update. check the [changelog](https://pub.dev/packages/wordpress_api#-changelog-tab-). Thanks for using and contributing to the package.

**Comment by ThinkDigitalSoftware** [comment]
Awesome! Thank you
