### ISSUE TITLE
More posts per page

### ISSUE THREAD

**Issue by Willi180** [dhmgroup/dart-wp#35]
Hello, how can I get more as 10 Post per page, Thanks

**Comment by theeomm** [comment]
Simply pass `args` with a `per_page` key. You can refer to the discussion [here](https://github.com/dhmgroup/dart-wp/discussions/17#discussioncomment-1739223). Hopefully this will be simplified in future updates

**Comment by Willi180** [comment]
> 

thank you very much, for your Answer!
