### ISSUE TITLE
Can't get data from WP API if endpoint contains forward slash (/)

### ISSUE THREAD

**Issue by jkclaudio20** [dhmgroup/dart-wp#4]
This code
`final posts = (await wordpress.getAsync('posts'))['data'];`
works fine.

But if you add a forward slash to the endpoint, flutter throws an exception:
Invalid argument(s): The source must not be null
Sample code: `final posts = (await wordpress.getAsync('posts/1'))['data'];`

**Comment by theeomm** [comment]
Thanks for reporting the issue. I will check the problem and provide the necessary update. Feel free to PR if you find a solution around it

**Comment by theeomm** [comment]
This issue has been fixed in the latest update [v0.1.3+1](https://pub.dev/packages/wordpress_api)
