### ISSUE TITLE
How to get the typed data when make a request?

### ISSUE THREAD

**Issue by CurrySenpai** [dhmgroup/dart-wp#6]
currently i am doing this 
```dart
    final WPResponse response = await api.getPosts();
    final List<PostSchema> posts =
        (response.data as List).map((e) => PostSchema.fromJson(e)).toList();
```
is there a less boilerplate way and safe?

thank you

**Comment by theeomm** [comment]
Will take this as a suggestion as this wasn't thought of when adding the schemas. Thank you for your contribution

**Comment by theeomm** [comment]
This has been done in the latest release. Thanks for the suggestion once more
