### ISSUE TITLE
Error in calling getPosts() method.

### ISSUE THREAD

**Issue by sharkpowah** [dhmgroup/dart-wp#8]
When i try to call wp.getPosts() method in my code, copy and pasted with necessary changes, I get the following:

```
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast
#0      _$PostSchemaFromJson 
package:wordpress_api/…/schemas/post.g.dart:32
#1      new PostSchema.fromJson 
package:wordpress_api/…/schemas/post.dart:131
#2      WordPressAPI.getPosts.<anonymous closure> 
[...]
```

EDIT: after trying to solve this problem, I temporary fixed this using the custom endpoint "method" to make it work, and it works. So as of now I can't tell if it's just a problem of mine or what. By the way, I'm still new to flutter, so it may be just a problem of mine...

**Comment by theeomm** [comment]
This should be fixed from [v0.2.1](https://pub.dev/packages/wordpress_api). Thank you for reporting this issue
